"""init_tables

Revision ID: 838c45836451
Revises: 
Create Date: 2026-07-21 11:19:11.947836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '838c45836451'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('cover_image', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=256), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('isbn', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('total_chapters', sa.Integer(), nullable=True),
    sa.Column('total_words', sa.Integer(), nullable=True),
    sa.Column('upload_device_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_file_hash'), 'books', ['file_hash'], unique=False)
    op.create_index(op.f('ix_books_upload_device_id'), 'books', ['upload_device_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=128), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_table('book_contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('spine_index', sa.Integer(), nullable=False),
    sa.Column('chapter_title', sa.String(length=512), nullable=True),
    sa.Column('href', sa.String(length=512), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('plain_text', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_contents_book_id'), 'book_contents', ['book_id'], unique=False)
    op.create_table('book_spine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('spine_index', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('is_linear', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_id'], ['book_contents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_spine_book_id'), 'book_spine', ['book_id'], unique=False)
    op.create_table('reading_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('spine_index', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('scroll_percent', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_id'], ['book_contents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'book_id', name='uq_device_book_progress')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_progress')
    op.drop_index(op.f('ix_book_spine_book_id'), table_name='book_spine')
    op.drop_table('book_spine')
    op.drop_index(op.f('ix_book_contents_book_id'), table_name='book_contents')
    op.drop_table('book_contents')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_books_upload_device_id'), table_name='books')
    op.drop_index(op.f('ix_books_file_hash'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
